# Generated by Django 5.0 on 2023-12-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='photo',
        ),
    ]
